apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - releases/kube-prometheus-stack.yaml
  - releases/loki-stack.yaml
  - releases/tempo.yaml
  - releases/otel-collector.yaml
