apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.*"
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: flux-system
  values:
    mode: deployment
    image:
      repository: otel/opentelemetry-collector
    config:
      receivers:
        otlp:
          protocols:
            grpc: {}
            http: {}
      processors:
        batch: {}
      exporters:
        logging:
          loglevel: debug
        otlp/tempo:
          endpoint: tempo.monitoring.svc.cluster.local:4317
          tls:
            insecure: true
      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [logging, otlp/tempo]
