apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: tempo
      version: "1.*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    tempo:
      receivers:
        jaeger: null
      storage:
        trace:
          backend: local
