global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'portfolio'
    static_configs:
      - targets: ['portfolio_service:8000']
        labels: {service: portfolio}
    metrics_path: /metrics
  - job_name: 'worker'
    static_configs:
      - targets: ['worker_service:8002']
        labels: {service: worker}
    metrics_path: /metrics
  - job_name: 'notification'
    static_configs:
      - targets: ['notification_service:8001']
        labels: {service: notification}
    metrics_path: /metrics
