apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-queue-scaler
spec:
  scaleTargetRef:
    name: worker-service
  pollingInterval: 5
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
    - type: redis
      metadata:
        address: redis.default.svc.cluster.local:6379
        listName: worker_tasks
        listLength: "10"
