apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-chart.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "hello-chart.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
